### ISSUE TITLE
"isActive" prop is false even while "when" is true

### ISSUE THREAD

**Issue by isma-funes** [sshyam-gupta/react-router-prompt#65]
I'm using a `ReactRouterPrompt` and it works most of the time. But when I go to the same page (the page that has the Prompt) but with different url parameters and after trying to leave that page, I do not see my popup.

I debugged and the "isActive" prop is false even if "when" and all conditions give true.

Any help with this?

Thanks!

**Comment by sshyam-gupta** [comment]
@isma-funes sorry for delay here, would you be able to share quick example on codesandbox?
I am planning to update the package to support react-router-dom >=v6.7, this would get fixed in it but it has breaking changes cz of new API's introduces in react-router-dom.
If provided I can fix this for previous versions as well.

**Comment by sshyam-gupta** [comment]
Closing this for now. Can reopen if required.
Thanks for reporting
